-- run_test.py: extra environment variables:
 - RCL_ASSERT_RMW_ID_MATCHES=rmw_fastrtps_cpp
 - RMW_IMPLEMENTATION=rmw_fastrtps_cpp
-- run_test.py: invoking following command in '/home/utkarsh/clearbot/demos_custom/image_tools/.obj-x86_64-linux-gnu':
 - /home/utkarsh/.pyenv/shims/python3 -m launch_testing.launch_test /home/utkarsh/clearbot/demos_custom/image_tools/.obj-x86_64-linux-gnu/test_showimage_cam2image__rmw_fastrtps_cpp_None.py --junit-xml=/home/utkarsh/clearbot/demos_custom/image_tools/.obj-x86_64-linux-gnu/test_results/image_tools_custom/test_showimage_cam2image__rmw_fastrtps_cpp.xunit.xml --package-name=image_tools_custom

[INFO] [launch]: All log files can be found below /home/utkarsh/.ros/log/2023-07-28-16-19-21-545344-crdesktop-341546
[INFO] [launch]: Default logging verbosity is set to INFO
Warning: Passing ready_fn as an argument to generate_test_description will be removed in a future release.  Include a launch_testing.actions.ReadyToTest action in the LaunchDescription instead.
test_reliable_qos (image_tools_custom.TestExecutablesDemo)
Test QoS settings for both processes work as expected. ... [INFO] [test_showimage-1]: process started with pid [341604]
[INFO] [test_cam2image-2]: process started with pid [341606]
[test_showimage-1] Subscribing to topic 'image'
[test_showimage-1] Subscribing to topic 'image'
[test_cam2image-2] Publishing data on topic 'image'
[test_cam2image-2] Could not open video stream
[ERROR] [test_cam2image-2]: process has died [pid 341606, exit code 1, cmd '/home/utkarsh/clearbot/demos_custom/image_tools/.obj-x86_64-linux-gnu/cam2image -r 1 -s 0 -b -f 5'].
[INFO] [test_showimage-1]: sending signal 'SIGINT' to process[test_showimage-1]
[test_showimage-1] signal_handler(signal_value=2)
[INFO] [test_showimage-1]: process has finished cleanly [pid 341604]
FAIL

======================================================================
FAIL: test_reliable_qos (image_tools_custom.TestExecutablesDemo)
Test QoS settings for both processes work as expected.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/utkarsh/clearbot/demos_custom/image_tools/.obj-x86_64-linux-gnu/test_showimage_cam2image__rmw_fastrtps_cpp_None.py", line 83, in test_reliable_qos
    proc_output.assertWaitFor(
  File "/opt/ros/foxy/lib/python3.8/site-packages/launch_testing/io_handler.py", line 146, in assertWaitFor
    assert success, 'Waiting for output timed out'
AssertionError: Waiting for output timed out

----------------------------------------------------------------------
Ran 1 test in 10.003s

FAILED (failures=1)

----------------------------------------------------------------------
Ran 0 tests in 0.000s

OK


-- run_test.py: return code 1
-- run_test.py: verify result file '/home/utkarsh/clearbot/demos_custom/image_tools/.obj-x86_64-linux-gnu/test_results/image_tools_custom/test_showimage_cam2image__rmw_fastrtps_cpp.xunit.xml'
